import { NavigationItem, UserRole } from '@/lib/types/dashboard';

export const navigationConfig: Record<UserRole, NavigationItem[]> = {
  'Support Worker': [
    {
      id: 'dashboard',
      title: 'Dashboard',
      href: '/dashboard',
      icon: 'LayoutDashboard',
      role: ['Support Worker'],
    },
    {
      id: 'shifts',
      title: 'My Shifts',
      href: '/shifts',
      icon: 'Calendar',
      role: ['Support Worker'],
      badge: 0,
    },
    {
      id: 'timesheets',
      title: 'Timesheets',
      href: '/timesheets',
      icon: 'Clock',
      role: ['Support Worker'],
    },
    {
      id: 'compliance',
      title: 'My Compliance',
      href: '/compliance',
      icon: 'Shield',
      role: ['Support Worker'],
      badge: 0,
    },
    {
      id: 'profile',
      title: 'My Profile',
      href: '/profile',
      icon: 'User',
      role: ['Support Worker'],
    },
  ],

  'Support Manager': [
    {
      id: 'dashboard',
      title: 'Dashboard',
      href: '/dashboard',
      icon: 'LayoutDashboard',
      role: ['Support Manager'],
    },
    {
      id: 'roster',
      title: 'Roster Management',
      href: '/roster',
      icon: 'Calendar',
      role: ['Support Manager'],
    },
    {
      id: 'staff',
      title: 'Staff Management',
      href: '/staff',
      icon: 'Users',
      role: ['Support Manager'],
    },
    {
      id: 'compliance',
      title: 'Compliance',
      href: '/compliance',
      icon: 'Shield',
      role: ['Support Manager'],
      badge: 0,
    },
    {
      id: 'tasks',
      title: 'Tasks',
      href: '/tasks',
      icon: 'CheckSquare',
      role: ['Support Manager'],
      badge: 0,
    },
    {
      id: 'reports',
      title: 'Reports',
      href: '/reports',
      icon: 'BarChart3',
      role: ['Support Manager'],
    },
  ],

  'Finance Manager': [
    {
      id: 'dashboard',
      title: 'Dashboard',
      href: '/dashboard',
      icon: 'LayoutDashboard',
      role: ['Finance Manager'],
    },
    {
      id: 'payroll',
      title: 'Payroll',
      href: '/payroll',
      icon: 'DollarSign',
      role: ['Finance Manager'],
    },
    {
      id: 'invoices',
      title: 'Invoices',
      href: '/invoices',
      icon: 'FileText',
      role: ['Finance Manager'],
      badge: 0,
    },
    {
      id: 'expenses',
      title: 'Expenses',
      href: '/expenses',
      icon: 'Receipt',
      role: ['Finance Manager'],
    },
    {
      id: 'reports',
      title: 'Financial Reports',
      href: '/reports',
      icon: 'BarChart3',
      role: ['Finance Manager'],
    },
    {
      id: 'settings',
      title: 'Finance Settings',
      href: '/settings',
      icon: 'Settings',
      role: ['Finance Manager'],
    },
  ],

  'IT Admin': [
    {
      id: 'dashboard',
      title: 'Dashboard',
      href: '/dashboard',
      icon: 'LayoutDashboard',
      role: ['IT Admin'],
    },
    {
      id: 'system',
      title: 'System Health',
      href: '/system',
      icon: 'Activity',
      role: ['IT Admin'],
    },
    {
      id: 'users',
      title: 'User Management',
      href: '/users',
      icon: 'Users',
      role: ['IT Admin'],
    },
    {
      id: 'devices',
      title: 'Device Inventory',
      href: '/devices',
      icon: 'Monitor',
      role: ['IT Admin'],
    },
    {
      id: 'tickets',
      title: 'Support Tickets',
      href: '/tickets',
      icon: 'MessageSquare',
      role: ['IT Admin'],
      badge: 0,
    },
    {
      id: 'settings',
      title: 'IT Settings',
      href: '/settings',
      icon: 'Settings',
      role: ['IT Admin'],
    },
  ],

  'System Admin': [
    {
      id: 'dashboard',
      title: 'Dashboard',
      href: '/dashboard',
      icon: 'LayoutDashboard',
      role: ['System Admin'],
    },
    {
      id: 'system',
      title: 'System Configuration',
      href: '/system',
      icon: 'Settings',
      role: ['System Admin'],
      children: [
        {
          id: 'database',
          title: 'Database',
          href: '/system/database',
          icon: 'Database',
          role: ['System Admin'],
        },
        {
          id: 'api',
          title: 'API Configuration',
          href: '/system/api',
          icon: 'Code',
          role: ['System Admin'],
        },
        {
          id: 'backup',
          title: 'Backup & Recovery',
          href: '/system/backup',
          icon: 'HardDrive',
          role: ['System Admin'],
        },
      ],
    },
    {
      id: 'users',
      title: 'User Management',
      href: '/users',
      icon: 'Users',
      role: ['System Admin'],
    },
    {
      id: 'roles',
      title: 'Role & Permissions',
      href: '/roles',
      icon: 'Shield',
      role: ['System Admin'],
    },
    {
      id: 'logs',
      title: 'System Logs',
      href: '/logs',
      icon: 'FileText',
      role: ['System Admin'],
    },
    {
      id: 'settings',
      title: 'System Settings',
      href: '/settings',
      icon: 'Settings',
      role: ['System Admin'],
    },
  ],

  'HR Manager': [
    {
      id: 'dashboard',
      title: 'Dashboard',
      href: '/dashboard',
      icon: 'LayoutDashboard',
      role: ['HR Manager'],
    },
    {
      id: 'hr',
      title: 'HR Management',
      href: '/hr',
      icon: 'Users',
      role: ['HR Manager'],
      children: [
        {
          id: 'employees',
          title: 'Employee Management',
          href: '/hr/employees',
          icon: 'User',
          role: ['HR Manager'],
        },
        {
          id: 'training',
          title: 'Training Management',
          href: '/hr/training',
          icon: 'GraduationCap',
          role: ['HR Manager'],
        },
        {
          id: 'leave',
          title: 'Leave Requests',
          href: '/hr/leave',
          icon: 'Calendar',
          role: ['HR Manager'],
          badge: 0,
        },
        {
          id: 'compliance',
          title: 'Compliance Reports',
          href: '/hr/compliance',
          icon: 'Shield',
          role: ['HR Manager'],
        },
        {
          id: 'recruitment',
          title: 'Recruitment',
          href: '/hr/recruitment',
          icon: 'UserPlus',
          role: ['HR Manager'],
        },
        {
          id: 'performance',
          title: 'Performance Reviews',
          href: '/hr/performance',
          icon: 'Star',
          role: ['HR Manager'],
        },
      ],
    },
    {
      id: 'reports',
      title: 'HR Reports',
      href: '/reports',
      icon: 'BarChart3',
      role: ['HR Manager'],
    },
    {
      id: 'settings',
      title: 'HR Settings',
      href: '/settings',
      icon: 'Settings',
      role: ['HR Manager'],
    },
  ],

  'Clinical Manager': [
    {
      id: 'dashboard',
      title: 'Dashboard',
      href: '/dashboard',
      icon: 'LayoutDashboard',
      role: ['Clinical Manager'],
    },
    {
      id: 'clients',
      title: 'Client Management',
      href: '/clients',
      icon: 'User',
      role: ['Clinical Manager'],
    },
    {
      id: 'care-plans',
      title: 'Care Plans',
      href: '/care-plans',
      icon: 'FileText',
      role: ['Clinical Manager'],
    },
    {
      id: 'appointments',
      title: 'Appointments',
      href: '/appointments',
      icon: 'Calendar',
      role: ['Clinical Manager'],
    },
    {
      id: 'incidents',
      title: 'Incidents',
      href: '/incidents',
      icon: 'AlertTriangle',
      role: ['Clinical Manager'],
      badge: 0,
    },
    {
      id: 'reports',
      title: 'Clinical Reports',
      href: '/reports',
      icon: 'BarChart3',
      role: ['Clinical Manager'],
    },
  ],

  'Service Delivery GM': [
    {
      id: 'dashboard',
      title: 'Dashboard',
      href: '/dashboard',
      icon: 'LayoutDashboard',
      role: ['Service Delivery GM'],
    },
    {
      id: 'properties',
      title: 'Properties',
      href: '/properties',
      icon: 'Building',
      role: ['Service Delivery GM'],
    },
    {
      id: 'staff',
      title: 'Staff Overview',
      href: '/staff',
      icon: 'Users',
      role: ['Service Delivery GM'],
    },
    {
      id: 'compliance',
      title: 'Compliance Overview',
      href: '/compliance',
      icon: 'Shield',
      role: ['Service Delivery GM'],
    },
    {
      id: 'quality',
      title: 'Service Quality',
      href: '/quality',
      icon: 'Star',
      role: ['Service Delivery GM'],
    },
    {
      id: 'reports',
      title: 'Executive Reports',
      href: '/reports',
      icon: 'BarChart3',
      role: ['Service Delivery GM'],
    },
  ],

  'CEO': [
    {
      id: 'dashboard',
      title: 'Dashboard',
      href: '/dashboard',
      icon: 'LayoutDashboard',
      role: ['CEO'],
    },
    {
      id: 'overview',
      title: 'Business Overview',
      href: '/overview',
      icon: 'BarChart3',
      role: ['CEO'],
    },
    {
      id: 'finance',
      title: 'Financial Overview',
      href: '/finance',
      icon: 'DollarSign',
      role: ['CEO'],
    },
    {
      id: 'operations',
      title: 'Operations',
      href: '/operations',
      icon: 'Settings',
      role: ['CEO'],
    },
    {
      id: 'reports',
      title: 'Executive Reports',
      href: '/reports',
      icon: 'FileText',
      role: ['CEO'],
    },
  ],
};

export const getNavigationForRole = (role: UserRole): NavigationItem[] => {
  return navigationConfig[role] || [];
};

export const getAllowedRoles = (): UserRole[] => {
  return Object.keys(navigationConfig) as UserRole[];
}; 